# Generated by Django 5.0 on 2025-08-10 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntn_cnic', models.CharField(blank=True, max_length=15, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('name', models.CharField(max_length=255)),
                ('province', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_type', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_code', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.CharField(max_length=255)),
                ('uo_m', models.CharField(blank=True, max_length=15, null=True)),
                ('purchase_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('sale_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('invoice_number', models.CharField(max_length=50)),
                ('invoice_number_fbr', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_ref_no', models.CharField(blank=True, max_length=50, null=True)),
                ('scenario_id', models.CharField(blank=True, max_length=50, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.customer')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(blank=True, max_length=10, null=True)),
                ('uo_m', models.CharField(blank=True, max_length=15, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('total_values', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True)),
                ('value_sales_excluding_st', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True)),
                ('fixed_notified_value_or_retail_price', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True)),
                ('sales_tax_applicable', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True)),
                ('sales_tax_withheld_at_source', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True)),
                ('extra_tax', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True)),
                ('further_tax', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True)),
                ('sro_schedule_no', models.CharField(blank=True, max_length=50, null=True)),
                ('fed_payable', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True)),
                ('sale_type', models.CharField(max_length=100)),
                ('sro_item_serial_no', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.item')),
            ],
        ),
    ]
