# Generated by Django 5.0 on 2025-08-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='extra_tax',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
