# Generated by Django 5.0 on 2025-08-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_invoiceitem_extra_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='extra_tax',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True),
        ),
    ]
