# Generated by Django 5.0 on 2025-09-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_alter_invoiceitem_extra_tax"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="uo_m",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
