# Generated by Django 5.0 on 2025-09-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_alter_item_uo_m"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="uo_m",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
